## ============================
## The OWP version does not need Taudem, so there is only one stage
FROM python:3.12-slim
ARG dataDir=/data
ENV projectDir=/foss_fim
ENV inputsDir=$dataDir/inputs
ENV outputsDir=/outputs
ENV srcDir=$projectDir/src
ENV toolsDir=$projectDir/tools
ENV workDir=/fim_temp

## ADDING FIM GROUP ##
## Skip for OWP Enviro
# ARG GroupID=1370800235
# ARG GroupName=fim
# RUN addgroup --gid $GroupID $GroupName
# ENV GID=$GroupID
# ENV GN=$GroupName

## ============================
## Create working directories
RUN mkdir -p $workDir

## adding environment variables for numba and python ##
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Prevents Python from writing .pyc files and keeps stdout/stderr unbuffered
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_ROOT_USER_ACTION=ignore

## ============================
## Install necessary packages
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    p7zip-full time parallel \
    build-essential libpq-dev libexpat1 \
    rsync tzdata wget bzip2 curl unzip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt auto-remove

RUN pip install --upgrade pip
RUN pip install --no-cache-dir pipenv
COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy --ignore-pipfile

# adding AWS CLI (for bash) ##
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip

# ----------------------------------
## ADD TO PATHS ##
ENV PATH="$projectDir:${PATH}"
ENV PYTHONPATH="${projectDir}:${srcDir}:${srcDir}/utils:${projectDir}/data:${toolsDir}"

## ============================
## Set default permissions
# RUN umask 0027

## ============================
## Set entrypoint
ADD ./src/entrypoint.sh /
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
