## Temporary image to build the libraries and only save the needed artifacts
FROM ghcr.io/osgeo/gdal:ubuntu-small-3.12.3 AS builder
WORKDIR /opt/builder
ARG depDir=/dependencies
ARG taudemVersion=98137bb6541a0d0077a9c95becfed4e56d0aa0ac
ARG taudemVersion2=81f7a07cdd3721617a30ee4e087804fddbcffa88
ENV taudemDir=$depDir/taudem/bin
ENV taudemDir2=$depDir/taudem_accelerated_flowDirections/taudem/build/bin

## ============================
## Fix APT permission issue
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends apt-utils && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

## ============================
## Install dependencies for compilation
RUN apt-get update && apt-get install -y --no-install-recommends \
    git cmake mpich libmpich-dev libgtest-dev libboost-test-dev libnetcdf-dev make gcc g++ \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

## ============================
## Clone repositories
RUN git clone https://github.com/dtarb/taudem.git
RUN git clone https://github.com/fernandoa123/cybergis-toolkit.git taudem_accelerated_flowDirections

## ============================
## Compile Main taudem repo ##
RUN mkdir -p taudem/bin
RUN cd taudem \
    && git checkout $taudemVersion \
    && cd src \
    && make

## ============================
## Compile taudem repo with accelerated flow directions ##
RUN cd taudem_accelerated_flowDirections/taudem \
    && git checkout $taudemVersion2 \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make

## ============================
## Move needed binaries to the next stage of the image
RUN mkdir -p $taudemDir
RUN mkdir -p $taudemDir2
RUN cd taudem/bin \
     && mv -t $taudemDir flowdircond streamnet gagewatershed catchhydrogeo dinfdistdown
RUN cd taudem_accelerated_flowDirections/taudem/build/bin \
     && mv -t $taudemDir2 d8flowdir dinfflowdir

## ============================
## Fix permissions before copying to final stage
RUN chown -R root:root $depDir && chmod -R 777 $depDir


###############################################################################################
# Base Image that has GDAL, PROJ, etc
FROM ghcr.io/osgeo/gdal:ubuntu-small-3.12.3
ARG dataDir=/data
ENV projectDir=/foss_fim
ARG depDir=/dependencies
ENV inputsDir=$dataDir/inputs
ENV outputsDir=/outputs
ENV srcDir=$projectDir/src
ENV toolsDir=$projectDir/tools
ENV workDir=/fim_temp
ENV taudemDir=$depDir/taudem/bin
ENV taudemDir2=$depDir/taudem_accelerated_flowDirections/taudem/build/bin

## ADDING FIM GROUP ##
ARG GroupID=1370800235
ARG GroupName=fim
RUN groupadd --gid $GroupID $GroupName
ENV GID=$GroupID
ENV GN=$GroupName

## ============================
## Create working directories
RUN mkdir -p $workDir
RUN mkdir -p $depDir

## ============================
## Fix COPY issue
COPY --from=builder $depDir $depDir
RUN chown -R root:root $depDir && chmod -R 777 $depDir

## adding environment variables for numba and python ##
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PYTHONUNBUFFERED=TRUE

## ============================
## Install necessary packages
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    p7zip-full python3.12 python3-pip python3-dev time parallel \
    mpich libmpich-dev libgeos-dev \
    make gcc g++ expect rsync tzdata wget bzip2 curl unzip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN apt auto-remove

## Python Environment Bypass (Required for Ubuntu 24.04/Python 3.12) ##
ENV PIP_BREAK_SYSTEM_PACKAGES=1 \
    PIP_IGNORE_INSTALLED=1 \
    PIPENV_SYSTEM=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_ROOT_USER_ACTION=ignore

ENV TZ=UTC
ENV MAMBA_ROOT_PREFIX=/opt/micromamba

# Install Pipenv with the break flag 
RUN python3 -m pip install --no-cache-dir pipenv --break-system-packages

# These currently throw errors as they are not yet installed
# by this point, but continues with the fresh install. Leaving upgrade error
# in place in case this order of installing changes later.
RUN python3 -m pip install --upgrade pip setuptools wheel

# Install a newer PDAL runtime than the Ubuntu package currently provides.
RUN wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj -C /usr/local/bin --strip-components=1 bin/micromamba && \
    micromamba create -y -p /opt/pdal-env -c conda-forge pdal=2.9.3 gdal proj proj-data && \
    micromamba clean --all --yes

# adding AWS CLI (for bash) ##
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip

# ----------------------------------
# Mar 2023 / Sep 2024
# There are some nuances in the whitebox python downloads in that the first time it loads
# it goes to the internet and downloads the latest/greatest WBT (whiteboxtools) engine which is
# required for the whitebox python library to work. We don't want to have FIM attempting a download
# each time a container is opened and the whitebox engine is called.
# Instead we will setup the WBT engine at time of docker build (same as Taudem and AWS).
# Whitebox code detects that the engine it there and makes no attempt to update it.
# We download and unzip it to the same file folder that pip deployed the whitebox library.
# Whitebox also attempts to always download a folder called testdata regardless of use.
# We added an empty folder to fake out whitebox_tools.py so it doesn't try to download the folder
ENV WBT_PATH=/usr/local/lib/python3.12/dist-packages/whitebox/WBT
RUN wget -P $WBT_PATH https://www.whiteboxgeo.com/WBT_Linux/WhiteboxTools_linux_musl.zip && \
    unzip -o $WBT_PATH/WhiteboxTools_linux_musl.zip -d $WBT_PATH && \
    cp $WBT_PATH/WhiteboxTools_linux_amd64/WBT/whitebox_tools $WBT_PATH
# ----------------------------------

## ADD TO PATHS ##
ENV PATH="$projectDir:${PATH}"
ENV PYTHONPATH="${projectDir}:${srcDir}:${srcDir}/utils:${projectDir}/data:${toolsDir}"

# ## install python 3 modules ##
COPY Pipfile Pipfile.lock ./
RUN pipenv install --deploy --system --ignore-pipfile

# CRITICAL: Reinstall Legacy Stack to prevent NumPy 2.x from breaking GDAL 
RUN python3 -m pip install --force-reinstall --break-system-packages \
    "numpy<2.0.0" \
    "scipy==1.13.1"

ENV PDAL_CLI_PATH="/opt/pdal-env/bin/pdal"
ENV PDAL_ENV_ROOT="/opt/pdal-env"

ADD ./src/entrypoint.sh /
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
