version: '3.5'
services:
  calibration-db:
    image: postgis/postgis
    container_name: fim_calibration_db
    restart: always
    environment:
      - POSTGRES_USER=${CALIBRATION_DB_USER_NAME}
      - POSTGRES_PASSWORD=${CALIBRATION_DB_PASS}
      - POSTGRES_DB=${CALIBRATION_DB_NAME}
      - PGDATA=/var/lib/postgresql/data/fim/pgdata
    ports:
      - "5432:5432"
    volumes:
      - calibration_db_data:/var/lib/postgresql/data/fim
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
    calibration_db_data:
