version: '3.5'
services:
  fim_node_connector:
    image: fim_node_connector
    build:
      context: ./connector
    container_name: fim_node_connector
    env_file:
      - .env
    restart: always
    expose:
      - "6000"
    networks:
      fim:
        aliases: 
          - fimnodeconnector
    volumes:
      - ${DATA_PATH}:/data/
      - /var/run/docker.sock:/var/run/docker.sock
  fim_node_updater:
    image: fim_node_updater
    build:
      context: ./updater
    container_name: fim_node_updater
    env_file:
      - .env
    restart: always
    depends_on: 
      - fim_node_connector
    networks:
      - fim
    volumes:
      - ${DATA_PATH}:/data/
      - /var/run/docker.sock:/var/run/docker.sock
  fim_nginx:
    image: nginx
    container_name: fim_nginx
    restart: always
    depends_on:
      - fim_node_connector
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - fim
    command: [nginx]

networks:
  fim:
    name: fim
          
      